spring:
  application:
    name: test-task
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/subscribedb}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  flyway:
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8080
